// <auto-generated />
using System;
using System.Collections.Generic;
using Calendario.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Calendario.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260116115856_AgregarCategoriaYColorAReglas")]
    partial class AgregarCategoriaYColorAReglas
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Calendario.Modelos.CalendarioDefinition", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Calendarios");
                });

            modelBuilder.Entity("Calendario.Modelos.Evento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("Inicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Eventos");
                });

            modelBuilder.Entity("Calendario.Modelos.ExcepcionRegla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaOriginal")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan?>("NuevaHoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan?>("NuevaHoraInicio")
                        .HasColumnType("interval");

                    b.Property<string>("NuevoTitulo")
                        .HasColumnType("text");

                    b.Property<int>("ReglaCalendarioId")
                        .HasColumnType("integer");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ReglaCalendarioId");

                    b.ToTable("Excepciones");
                });

            modelBuilder.Entity("Calendario.Modelos.ReglaCalendario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<int?>("CalendarioDefinitionId")
                        .HasColumnType("integer");

                    b.Property<int>("CalendarioId")
                        .HasColumnType("integer");

                    b.Property<string>("Categoria")
                        .HasColumnType("text");

                    b.Property<string>("Color")
                        .HasColumnType("text");

                    b.Property<List<int>>("DiasSemana")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.Property<DateTime>("FechaFin")
                        .HasColumnType("timestamp without time zone");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<TimeSpan>("HoraFin")
                        .HasColumnType("interval");

                    b.Property<TimeSpan>("HoraInicio")
                        .HasColumnType("interval");

                    b.Property<int>("Tipo")
                        .HasColumnType("integer");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CalendarioDefinitionId");

                    b.ToTable("Reglas");
                });

            modelBuilder.Entity("Calendario.Modelos.ExcepcionRegla", b =>
                {
                    b.HasOne("Calendario.Modelos.ReglaCalendario", null)
                        .WithMany("Excepciones")
                        .HasForeignKey("ReglaCalendarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Calendario.Modelos.ReglaCalendario", b =>
                {
                    b.HasOne("Calendario.Modelos.CalendarioDefinition", null)
                        .WithMany("Reglas")
                        .HasForeignKey("CalendarioDefinitionId");
                });

            modelBuilder.Entity("Calendario.Modelos.CalendarioDefinition", b =>
                {
                    b.Navigation("Reglas");
                });

            modelBuilder.Entity("Calendario.Modelos.ReglaCalendario", b =>
                {
                    b.Navigation("Excepciones");
                });
#pragma warning restore 612, 618
        }
    }
}
